# Site settings
baseurl = "https://jsilva.github.io/"
languageCode = "en-us"
title = "João Da Silva"
theme = "hugo-me-theme"
paginate = 5
paginatePath = "page"
preservetaxonomynames = true
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXX-Y"

[taxonomies]
tag = "tags"
category = "categories"

[params]
    
  # You may choose a color scheme for your site.
    # Available schemes are: gray, red, orange, yellow, green, cyan, blue, magenta, brown
    colorscheme = "red"
    
    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    author = "João Da Silva"
    description = "Software Developer"
    keywords = "scala, akka, playframework, finagle, ansible, spark, neo4j, cassandra, kafka"
    
    # Sidebar
    # Main settings
    [params.sidebar]
        name = "João Da Silva"
        description = "Software Developer, Designer, Capoeirista, DJ and Music Producer."
        avatar = "http://2.gravatar.com/avatar/b466034505109f11935c077faa605d7c?s=200&d=mm&r=g"
    
    # Navigation
    [[params.sidebar.navigation]]
        label = "About"
        link = "/about"

    # [[params.sidebar.navigation]]
    #     label = "Skills"
    #     link = "/skills"

    # [[params.sidebar.navigation]]
    #     label = "Projects"
    #     link = "/works"

    [[params.sidebar.navigation]]
        label = "Hire Me"
        link = "/contact"
    
    # Social links
    # [[params.sidebar.social]]
    #     label = "Twitter"
    #     icon = "fa-twitter"
    #     link = "#"

    # [[params.sidebar.social]]
    #     label = "Facebook"
    #     icon = "fa-facebook"
    #     link = "#"
        
    # [[params.sidebar.social]]
    #     label = "Instagram"
    #     icon = "fa-instagram"
    #     link = "#"
        
    [[params.sidebar.social]]
        label = "Github"
        icon = "fa-github"
        link = "https://github.com/JSilva"
        
    # [[params.sidebar.social]]
    #     label = "Email"
    #     icon = "fa-envelope"
    #     link = "#"
    
    # About page
    [params.about]
        title = "Joao Da Silva"
        intro = "Software Developer, Designer, Capoeirista, DJ and Music Producer. Creativity is my search."
        text = """
Software Developer and Team Lead. 

I have wide experience in frontend, backend and devops development for more than seven years in middle and long-term projects. My primary expertise includes a number of industry-proof technologies around the Scala ecosystem and the Lightbend Reactive platform  such as Akka, Playframework, Apache Spark.

I also have  good skills  in distributed systems development, computer vision, natural language processing, graph databases  and Ansible for systems provision. 

Looking for remote software development contract work. I can provide you with my personal services, or as a Lead of the team of my assistants from Czech Republic. 

[Hire me](/contact)
                """

    # # Skills page
    # [params.skills]
    #     title ="Things I Can Do For You"
    #     intro = "I can present you, your skills and works to the whole world."

    #     # List of skills or features or services
    #     [[params.skills.list]]
    #         icon = "fa-user"
    #         description = "Show your avatar"

    #     [[params.skills.list]]
    #         icon = "fa-list"
    #         description = "Tell about your skills"

    #     [[params.skills.list]]
    #         icon = "fa-picture-o"
    #         description = "Perform your works"

    #     [[params.skills.list]]
    #         icon = "fa-envelope"
    #         description = "Communicate with your visitors"

    #     [[params.skills.list]]
    #         icon = "fa-link"
    #         description = "Link your socials"
    
    #     [[params.skills.list]]
    #         icon = "fa-usd"
    #         description = "Make you rich. Joke. Not Me."
            
    # Works page
    [params.works]
        title ="Projects"
        intro = ""
        
        # [[params.works.show]]
        #     title = "Red Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "red.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"
            
        # [[params.works.show]]
        #     title = "Orange Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "orange.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"
            
        # [[params.works.show]]
        #     title = "Green Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "green.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"

        # [[params.works.show]]
        #     title = "Yellow Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "yellow.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"
        
        # [[params.works.show]]
        #     title = "Blue Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "blue.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"
            
        # [[params.works.show]]
        #     title = "Magenta Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "magenta.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"
            
        # [[params.works.show]]
        #     title = "Cyan Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "cyan.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"

        # [[params.works.show]]
        #     title = "Brown Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "brown.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"

        # [[params.works.show]]
        #     title = "Gray Color Scheme"
        #     description = "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
        #     image = "gray.png"
        #     link = "https://github.com/aerohub/hugo-me-theme"
    
    # Contact page
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    email = "joao@codedefinition.com"
    
    [params.contact]
        title ="Hire Me"
        intro = "Looking forward to connect with you."
        # Since this theme is static, the contact form uses [Formspree](http://www.formspree.io) as a proxy
        buttonText = "Send Message"
        resetText = "Reset Form"
        
        # 'warning' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name *"
            warning = "Please, enter your name"

        [params.contact.form.email]
            text = "Email *"
            warning = "Please, enter your email."

        [params.contact.form.phone]
            text = "Subject"

        [params.contact.form.message]
            text = "Message *"
            warning = "Please, enter your message"

    # 404 page
    [params.error]
        title = "404"
        intro = "Oops... Page not found!"
        text = "We are sorry, but the page you are looking for might have been:\n\n - removed,\n - had its name changed\n - or is temporarily unavailable."

    # Footer
    [params.footer]
        copyright = "All rights reserved."